In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
from google.colab import files
uploaded = files.upload()


Saving homeprice.csv to homeprice.csv


In [4]:
import io
df = pd.read_csv(io.BytesIO(uploaded['homeprice.csv']))
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [5]:
import math
medianFloor= math.floor(df.bedroom.median())

In [6]:
df.bedroom = df.bedroom.fillna(medianFloor)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [8]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_

383724.99999999994

In [10]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [11]:
137.25*3000 + -26025*3 + -6825*40 + 383724.99999999994

444399.99999999994

In [12]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

Exercise: Predict Salary

In [2]:
from google.colab import files
exerciseFile = files.upload()

Saving exercise1.csv to exercise1.csv


In [6]:
import io
td = pd.read_csv(io.BytesIO(exerciseFile['exercise1.csv']))
td

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [7]:
medianScore= td.test_score.median()
medianScore

8.0

In [8]:
td.test_score = td.test_score.fillna(medianScore)

In [9]:
td.experience = td.experience.fillna('zero')

In [10]:
td

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [11]:
pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=19d7da9f61a30def0e91b45300eb35accfa7bb46c22b417fc8e77ede0a764150
  Stored in directory: /root/.cache/pip/wheels/cb/f3/5a/d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number


In [12]:
from word2number import w2n
w2n.word_to_num('five')

5

In [13]:
td.experience = td.experience.apply(w2n.word_to_num)
td

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [17]:
reg = linear_model.LinearRegression()
reg.fit(td[['experience','test_score','interview_score']],td['salary'])

LinearRegression()

In [18]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [19]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])